src/Entity/Location.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LocationRepository")
 * @UniqueEntity("titre")
 * @Vich\Uploadable
 */
class Location
{
    const Chauffage = [
        0 => 'Electric',
        1 => 'Gaz'
    ];
    
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * @var File|null
     * @Assert\Image(
     *  mimeTypes="image/jpeg")
     * @Vich\UploadableField(mapping="location_image", fileNameProperty="filename")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $pieces;

    /**
     * @ORM\Column(type="integer")
     */
    private $chambres;

    /**
     * @ORM\Column(type="integer")
     */
    private $etage;

    /**
     * @ORM\Column(type="integer")
     */
    private $prix;

    /**
     * @ORM\Column(type="integer")
     */
    private $chauffage;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $addresse;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $code_postal;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $louer = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Option", inversedBy="locations")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->options = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->titre); // hello-world
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getPieces(): ?int
    {
        return $this->pieces;
    }

    public function setPieces(int $pieces): self
    {
        $this->pieces = $pieces;

        return $this;
    }

    public function getChambres(): ?int
    {
        return $this->chambres;
    }

    public function setChambres(int $chambres): self
    {
        $this->chambres = $chambres;

        return $this;
    }

    public function getEtage(): ?int
    {
        return $this->etage;
    }

    public function setEtage(int $etage): self
    {
        $this->etage = $etage;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }
    public function getFormattedPrix(): string
    {
        return number_format($this->prix, 0, '', ' ');
    }

    public function getChauffage(): ?int
    {
        return $this->chauffage;
    }

    public function setChauffage(int $chauffage): self
    {
        $this->chauffage = $chauffage;

        return $this;
    }

    public function getChauffageType(): string
    {
        return self::Chauffage[$this->chauffage];
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getAddresse(): ?string
    {
        return $this->addresse;
    }

    public function setAddresse(string $addresse): self
    {
        $this->addresse = $addresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getLouer(): ?bool
    {
        return $this->louer;
    }

    public function setLouer(bool $louer): self
    {
        $this->louer = $louer;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addLocation($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option))
        {
            $this->options->removeElement($option);
            $option->removeLocation($this);
        }

        return $this;
    }

    /**
     * @return null|string
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param null|string $filename
     * @return Location
     */
    public function setFilename(?string $filename): Location
      {
          $this->filename = $filename;
          return $this;
      }

      /**
       * @return null|File
       */
      public function getImageFile(): ?File
      {
          return $this->imageFile;
      }

      /**
       * @param null|File $imageFile
       * @return Location
       */
      public function setImageFile(?File $imageFile): Location
      {
          $this->imageFile = $imageFile;
          if( $this->imageFile instanceof UploadedFile)
          {
              $this->updated_at = new \DateTime('now');
          }
          return $this;
      }

      public function getUpdatedAt(): ?\DateTimeInterface
      {
          return $this->updated_at;
      }

      public function setUpdatedAt(\DateTimeInterface $updated_at): self
      {
          $this->updated_at = $updated_at;

          return $this;
      }
    
}

src/Entity/Option.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OptionRepository")
 * @Orm\Table(name="`Option`")
 */
class Option
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Location", mappedBy="options")
     */
    private $locations;

    public function __construct()
    {
        $this->locations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    /**
     * @return Collection|Location[]
     */
    public function getLocations(): Collection
    {
        return $this->locations;
    }

    public function addLocation(Location $location): self
    {
        if (!$this->locations->contains($location)) {
            $this->locations[] = $location;
        }

        return $this;
    }

    public function removeLocation(Location $location): self
    {
        if ($this->locations->contains($location)) {
            $this->locations->removeElement($location);
        }

        return $this;
    }
}

src/Form/LocationType.php
<?php

namespace App\Form;

use App\Entity\Location;
use App\Entity\Option;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class LocationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titre')
            ->add('description')
            ->add('surface')
            ->add('pieces')
            ->add('chambres')
            ->add('etage')
            ->add('prix')
            ->add('chauffage', ChoiceType::class, [
                'choices' => $this->getChoices()
            ])
            ->add('options', EntityType::class, [
                'class' => Option::class,
                'required' => false,
                'choice_label' => 'nom',
                'multiple' => true
            ])
            ->add('imageFile', FileType::class, [
                'required' => false
            ])
            ->add('ville')
            ->add('addresse')
            ->add('code_postal')
            ->add('louer')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Location::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getChoices()
    {
        $choices = Location::Chauffage;
        $output = [];
        foreach($choices as $k => $v) {
            $output[$v] = $k;
        }
        return $output;
    }
}

src/Controller/LocationController.php
<?php

namespace App\Controller;
 
use App\Entity\Location;
use App\Entity\LocationRecherche;
use App\Form\LocationRechercheType;
use App\Repository\LocationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Query;

use Knp\Component\Pager\PaginatorInterface;


class LocationController extends AbstractController
{
    /**
     * @var LocationRepository
     */
    private $repository;
    /**
     * @var ObjectManager
     */
    private $em;

    public function __construct(LocationRepository $repository, ObjectManager $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }

    /**
     * @Route("/biens", name="location.index")
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $recherche = new LocationRecherche();
        $form = $this->createForm(LocationRechercheType::class, $recherche);
        $form->handleRequest($request);
        // création entité notre recherche
        // creation formulaire de recherche
        // traitement du controlleur
        $locations = $paginator->paginate(
            $this->repository->findAllVisibleQuery($recherche),
            $request->query->getInt('page', 1),
            12
        );
        return $this->render('location/index.html.twig', [
            'current-menu' => 'locations',
            'locations'=> $locations,
            'form' => $form->createView()
            ]);
    }

    /**
     * @Route("/biens/{slug}-{id}", name="location.show", requirements={"slug": "[a-z0-9\-]*"})
     * @param Location $location
     * @return Response
     */
    public function show(Location $location, string $slug): Response
    {
        if ($location->getSlug() !== $slug)
        {
            $this->redirectToRoute('location.show', [
                'id' => $location->getId(),
                'slug' => $location->getSlug()
            ], 301);
        }
        return $this->render('location/show.html.twig', [
            'location' => $location,
            'current_menu' => 'locations'
        ]);
    }
}

templates/location/_location.html.twig

<div class="card mb-4">
    {% if location.filename %}
        <img src="{{ vich_uploader_asset(location, 'imageFile') | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height: auto;">
        {% else %}
        <img src="{{ '/images/locations/empty.jpg'| imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height: auto;">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ path('location.show', {slug: location.slug, id: location.id}) }}">
                {{ location.titre }}
            </a>
        </h5>
        <p class="card-text">{{ location.surface}} m² - {{ location.ville }} ({{ location.codepostal}})</p>
        <div class="text-primary" style="font-size: 2rem; font-weight: bold;">
            {{ location.formattedPrix }} €
        </div>
    </div>
</div>

templates/location/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Toutes nos locations' %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            {{ form_start(form) }}
            <div class="form-row">
                <div class="col">
                    {{ form_row(form.surfaceMin) }}
                </div>
                <div class="col">
                    {{ form_row(form.prixMax) }}
                </div>
                <div class="col">
                    {{ form_row(form.options) }}
                </div>
                <div class="col">
                    <div class="form-group">
                        <button class="btn btn-primary">Recherche</button>
                    </div>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>        
    <div class="container mt-4">

        <h1>Voir tous nos biens</h1>

        <div class="row">

        {% for location in locations %}
            <div class="col-md-4">
            {% include 'location/_location.html.twig' %}
            </div>
        {% endfor %}
        </div>

        <div class="pagination">
            {{ knp_pagination_render(locations) }}
        </div>
    </div>
{% endblock %}

templates/location/show.html.twig
{% extends 'base.html.twig' %}

{% block title location.titre %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    {% if location.filename %}
                        <img src="{{ vich_uploader_asset(location, 'imageFile') | imagine_filter('medium') }}" alt="card-img-top" style="width: 100%; height: auto;">
                        {% else %}
                        <img src="{{ '/images/locations/empty.jpg'| imagine_filter('medium') }}" alt="card-img-top" style="width: 100%; height: auto;">
                    {% endif %}
                </div>
                <div class="col-md-4">
                    <h1>{{ location.titre }}</h1>
                    <h2>{{ location.pieces}} pièces - {{ location.surface}} m²</h2>
                    <div class="text-primary" style="font-size: 4rem;font-weight: bold;">{{ location.formattedPrix }} €</div>
                    <a href="#" class="btn btn-primary">Contacter l'agence</a>
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-4">
    
    <p>{{ location.description | nl2br }}</p>

    <div class="row">
        <div class="col-md-8">
            <h2>Caractèristiques du biens</h2>
            <table class="table table-striped">
                <tr>
                    <td>Surface habitable</td>
                    <td>{{ location.surface }} m²</td>
                </tr>
                 <tr>
                    <td>Pièces</td>
                    <td>{{ location.pieces }}</td>
                </tr>
                 <tr>
                    <td>Chambres</td>
                    <td>{{ location.chambres }}</td>
                </tr>
                 <tr>
                    <td>etage</td>
                    <td>{{ location.etage }}</td>
                </tr>
                 <tr>
                    <td>Chauffage</td>
                    <td>{{ location.chauffageType }}</td>
                </tr>
            </table>
        </div>
        <div class="col-md-4">
            <h2>Spécificités</h2>
            <ul class="list-group">
                {% for option in location.options %}
                <li class="list-group-item">{{ option.nom }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>

    </div>
{% endblock %}